### ISSUE TITLE
attention计算问题

### ISSUE THREAD

**Issue by BlueSkyBubble** [songyingxin/NLP-Pytorch#3]
LSTM_ATT/LSTMATT.py文件中的第42行score = torch.tanh(torch.matmul(outputs, self.W_w))，为什么用双向LSTM的output与一个参数矩阵相乘就是score？请问这里确定没有问题？如果没有问题请给解答一下这里得到score的原理，十分感谢！

**Comment by songyingxin** [comment]
这个就是为了判断哪个lstm状态的输出最重要，因此这么设计。 这里设计的好处在于简单，没有其他复杂机制。你也可以变换，但效果并不一定。如果不懂的话可以看看我的文章：
https://zhuanlan.zhihu.com/p/59698165
